import { Holding, SoldHolding } from './entities/holding.entity';

export const PORTFOLIO_HOLDINGS: Holding[] = [
  // ── Financials ──
  {
    id: '1',
    particulars: 'HDFC Bank',
    sector: 'Financials',
    exchange: 'NSE',
    ticker: 'HDFCBANK.NS',
    googleTicker: 'NSE:HDFCBANK',
    purchasePrice: 1490,
    quantity: 50,
    marketCap: 1300795,
    debtToEquity: 7,
    stage2: true,
  },
  {
    id: '2',
    particulars: 'Bajaj Finance',
    sector: 'Financials',
    exchange: 'NSE',
    ticker: 'BAJFINANCE.NS',
    googleTicker: 'NSE:BAJFINANCE',
    purchasePrice: 6466,
    quantity: 15,
    marketCap: 521012,
    debtToEquity: 4,
    stage2: false,
  },
  {
    id: '3',
    particulars: 'ICICI Bank',
    sector: 'Financials',
    exchange: 'NSE',
    ticker: 'ICICIBANK.NS',
    googleTicker: 'NSE:ICICIBANK',
    purchasePrice: 780,
    quantity: 84,
    marketCap: 859583,
    debtToEquity: 6,
    stage2: true,
  },
  {
    id: '4',
    particulars: 'Bajaj Housing',
    sector: 'Financials',
    exchange: 'NSE',
    ticker: 'BAJAJHFL.NS',
    googleTicker: 'NSE:BAJAJHFL',
    purchasePrice: 130,
    quantity: 504,
    marketCap: 138017,
    debtToEquity: 6,
    stage2: false,
  },
  {
    id: '5',
    particulars: 'Savani Financials',
    sector: 'Financials',
    exchange: 'BSE',
    ticker: 'SAVANIFINL.BO',
    googleTicker: 'BSE:511577',
    purchasePrice: 24,
    quantity: 1080,
    marketCap: null,
    debtToEquity: null,
    stage2: false,
  },

  // ── Technology ──
  {
    id: '6',
    particulars: 'Affle India',
    sector: 'Technology',
    exchange: 'NSE',
    ticker: 'AFFLE.NS',
    googleTicker: 'NSE:AFFLE',
    purchasePrice: 1151,
    quantity: 50,
    marketCap: 20489,
    debtToEquity: 0,
    stage2: true,
  },
  {
    id: '7',
    particulars: 'LTI Mindtree',
    sector: 'Technology',
    exchange: 'NSE',
    ticker: 'LTIM.NS',
    googleTicker: 'NSE:LTIM',
    purchasePrice: 4775,
    quantity: 16,
    marketCap: 173004,
    debtToEquity: 0,
    stage2: false,
  },
  {
    id: '8',
    particulars: 'KPIT Tech',
    sector: 'Technology',
    exchange: 'NSE',
    ticker: 'KPITTECH.NS',
    googleTicker: 'NSE:KPITTECH',
    purchasePrice: 672,
    quantity: 61,
    marketCap: 35073,
    debtToEquity: 0,
    stage2: false,
  },
  {
    id: '9',
    particulars: 'Tata Tech',
    sector: 'Technology',
    exchange: 'NSE',
    ticker: 'TATATECH.NS',
    googleTicker: 'NSE:TATATECH',
    purchasePrice: 1072,
    quantity: 63,
    marketCap: 26879,
    debtToEquity: 0,
    stage2: false,
  },
  {
    id: '10',
    particulars: 'BLS E-Services',
    sector: 'Technology',
    exchange: 'BSE',
    ticker: 'BLSE.BO',
    googleTicker: 'BSE:544107',
    purchasePrice: 232,
    quantity: 191,
    marketCap: 1388,
    debtToEquity: 0,
    stage2: true,
  },
  {
    id: '11',
    particulars: 'Tanla Platforms',
    sector: 'Technology',
    exchange: 'NSE',
    ticker: 'TANLA.NS',
    googleTicker: 'NSE:TANLA',
    purchasePrice: 1134,
    quantity: 45,
    marketCap: 6041,
    debtToEquity: 0,
    stage2: false,
  },

  // ── Consumer ──
  {
    id: '12',
    particulars: 'DMart',
    sector: 'Consumer',
    exchange: 'NSE',
    ticker: 'DMART.NS',
    googleTicker: 'NSE:DMART',
    purchasePrice: 3777,
    quantity: 27,
    marketCap: 224584,
    debtToEquity: 0,
    stage2: false,
  },
  {
    id: '13',
    particulars: 'Tata Consumer',
    sector: 'Consumer',
    exchange: 'NSE',
    ticker: 'TATACONSUM.NS',
    googleTicker: 'NSE:TATACONSUM',
    purchasePrice: 845,
    quantity: 90,
    marketCap: 97066,
    debtToEquity: 0,
    stage2: false,
  },
  {
    id: '14',
    particulars: 'Pidilite',
    sector: 'Consumer',
    exchange: 'NSE',
    ticker: 'PIDILITIND.NS',
    googleTicker: 'NSE:PIDILITIND',
    purchasePrice: 2376,
    quantity: 36,
    marketCap: 138857,
    debtToEquity: 0,
    stage2: false,
  },

  // ── Power ──
  {
    id: '15',
    particulars: 'Tata Power',
    sector: 'Power',
    exchange: 'NSE',
    ticker: 'TATAPOWER.NS',
    googleTicker: 'NSE:TATAPOWER',
    purchasePrice: 224,
    quantity: 225,
    marketCap: 112140,
    debtToEquity: 2,
    stage2: false,
  },
  {
    id: '16',
    particulars: 'KPI Green',
    sector: 'Power',
    exchange: 'BSE',
    ticker: 'KPIGREEN.BO',
    googleTicker: 'BSE:542323',
    purchasePrice: 875,
    quantity: 50,
    marketCap: 7915,
    debtToEquity: 1,
    stage2: false,
  },
  {
    id: '17',
    particulars: 'Suzlon Energy',
    sector: 'Power',
    exchange: 'NSE',
    ticker: 'SUZLON.NS',
    googleTicker: 'NSE:SUZLON',
    purchasePrice: 44,
    quantity: 450,
    marketCap: 70108,
    debtToEquity: 0,
    stage2: false,
  },
  {
    id: '18',
    particulars: 'Gensol Engg',
    sector: 'Power',
    exchange: 'BSE',
    ticker: 'GENSOL.BO',
    googleTicker: 'BSE:542851',
    purchasePrice: 998,
    quantity: 45,
    marketCap: 6985,
    debtToEquity: 5,
    stage2: false,
  },

  // ── Pipes ──
  {
    id: '19',
    particulars: 'Hariom Pipe',
    sector: 'Pipes',
    exchange: 'BSE',
    ticker: 'HARIOMPIPE.BO',
    googleTicker: 'BSE:543517',
    purchasePrice: 580,
    quantity: 60,
    marketCap: 1094,
    debtToEquity: 1,
    stage2: false,
  },
  {
    id: '20',
    particulars: 'Astral',
    sector: 'Pipes',
    exchange: 'NSE',
    ticker: 'ASTRAL.NS',
    googleTicker: 'NSE:ASTRAL',
    purchasePrice: 1517,
    quantity: 56,
    marketCap: 35397,
    debtToEquity: 0,
    stage2: false,
  },
  {
    id: '21',
    particulars: 'Polycab',
    sector: 'Pipes',
    exchange: 'NSE',
    ticker: 'POLYCAB.NS',
    googleTicker: 'NSE:POLYCAB',
    purchasePrice: 2818,
    quantity: 28,
    marketCap: 75253,
    debtToEquity: 0,
    stage2: true,
  },

  // ── Others ──
  {
    id: '22',
    particulars: 'Clean Science',
    sector: 'Others',
    exchange: 'BSE',
    ticker: 'CLEAN.BO',
    googleTicker: 'BSE:543318',
    purchasePrice: 1610,
    quantity: 32,
    marketCap: 13158,
    debtToEquity: 0,
    stage2: false,
  },
  {
    id: '23',
    particulars: 'Deepak Nitrite',
    sector: 'Others',
    exchange: 'NSE',
    ticker: 'DEEPAKNTR.NS',
    googleTicker: 'NSE:DEEPAKNTR',
    purchasePrice: 2248,
    quantity: 27,
    marketCap: 16138,
    debtToEquity: 0,
    stage2: false,
  },
  {
    id: '24',
    particulars: 'Fine Organic',
    sector: 'Others',
    exchange: 'BSE',
    ticker: 'FINEORG.BO',
    googleTicker: 'BSE:541557',
    purchasePrice: 4284,
    quantity: 16,
    marketCap: 16138,
    debtToEquity: 0,
    stage2: false,
  },
  {
    id: '25',
    particulars: 'Gravita India',
    sector: 'Others',
    exchange: 'NSE',
    ticker: 'GRAVITA.NS',
    googleTicker: 'NSE:GRAVITA',
    purchasePrice: 2037,
    quantity: 8,
    marketCap: 16138,
    debtToEquity: 1,
    stage2: false,
  },
  {
    id: '26',
    particulars: 'SBI Life',
    sector: 'Others',
    exchange: 'NSE',
    ticker: 'SBILIFE.NS',
    googleTicker: 'NSE:SBILIFE',
    purchasePrice: 1197,
    quantity: 49,
    marketCap: 140000,
    debtToEquity: 0,
    stage2: false,
  },
];

// ── Exited / Sold Positions (from Excel) ──
export const SOLD_HOLDINGS: SoldHolding[] = [
  {
    id: 's1',
    particulars: 'Infosys',
    ticker: 'INFY.NS',
    sector: 'Technology',
    purchasePrice: 1647,
    quantity: 36,
    soldPrice: 1452,
    investment: 1647 * 36,
    saleValue: 1452 * 36,
    realizedPnL: (1452 - 1647) * 36,
    realizedPnLPct: ((1452 - 1647) / 1647) * 100,
  },
  {
    id: 's2',
    particulars: 'Happiest Minds',
    ticker: 'HAPPSTMNDS.NS',
    sector: 'Technology',
    purchasePrice: 1103,
    quantity: 45,
    soldPrice: 716,
    investment: 1103 * 45,
    saleValue: 716 * 45,
    realizedPnL: (716 - 1103) * 45,
    realizedPnLPct: ((716 - 1103) / 1103) * 100,
  },
  {
    id: 's3',
    particulars: 'EaseMyTrip',
    ticker: 'EASEMYTRIP.NS',
    sector: 'Consumer',
    purchasePrice: 20,
    quantity: 1332,
    soldPrice: 15.5,
    investment: 20 * 1332,
    saleValue: 15.5 * 1332,
    realizedPnL: (15.5 - 20) * 1332,
    realizedPnLPct: ((15.5 - 20) / 20) * 100,
  },
];

// ── Static Fundamentals fallback (from Excel) ──
export const STATIC_FUNDAMENTALS: Record<
  string,
  { peRatio: number | null; latestEarnings: string | null }
> = {
  'NSE:HDFCBANK': { peRatio: 18.69, latestEarnings: '₹91.02' },
  'NSE:BAJFINANCE': { peRatio: 32.63, latestEarnings: '₹257.80' },
  'NSE:ICICIBANK': { peRatio: 17.68, latestEarnings: '₹68.72' },
  'NSE:BAJAJHFL': { peRatio: 85.72, latestEarnings: '₹2.53' },
  'BSE:511577': { peRatio: null, latestEarnings: null },
  'NSE:AFFLE': { peRatio: 55.53, latestEarnings: '₹26.11' },
  'NSE:LTIM': { peRatio: 34.69, latestEarnings: '₹145.92' },
  'NSE:KPITTECH': { peRatio: 46.57, latestEarnings: '₹27.77' },
  'NSE:TATATECH': { peRatio: 41.68, latestEarnings: '₹15.88' },
  'BSE:544107': { peRatio: 26.3, latestEarnings: '₹5.80' },
  'NSE:TANLA': { peRatio: 11.64, latestEarnings: '₹39.48' },
  'NSE:DMART': { peRatio: 82.63, latestEarnings: '₹41.75' },
  'NSE:TATACONSUM': { peRatio: 26.56, latestEarnings: '₹134.77' },
  'NSE:PIDILITIND': { peRatio: 71.13, latestEarnings: '₹38.36' },
  'NSE:TATAPOWER': { peRatio: 29.36, latestEarnings: '₹11.94' },
  'BSE:542323': { peRatio: 29.26, latestEarnings: '₹13.75' },
  'NSE:SUZLON': { peRatio: 61.25, latestEarnings: '₹0.84' },
  'BSE:542851': { peRatio: 39.51, latestEarnings: '₹5.57' },
  'BSE:543517': { peRatio: 17.98, latestEarnings: '₹19.78' },
  'NSE:ASTRAL': { peRatio: 67.13, latestEarnings: '₹19.59' },
  'NSE:POLYCAB': { peRatio: 40.91, latestEarnings: '₹121.97' },
  'BSE:543318': { peRatio: 50.37, latestEarnings: '₹24.52' },
  'NSE:DEEPAKNTR': { peRatio: 41.86, latestEarnings: '₹37.26' },
  'BSE:541557': { peRatio: 41.86, latestEarnings: '₹37.26' },
  'NSE:GRAVITA': { peRatio: 41.86, latestEarnings: '₹37.26' },
  'NSE:SBILIFE': { peRatio: null, latestEarnings: '₹-5.82' },
};
